
title: The Close AGN Reference Survey
description: CARS is a survey of nearby (z<0.05) unobscured AGN. 41 galaxies were observed with MUSE and complemented
  by many multi-wavelength observations.
logo: "/images/cars_blue.png?raw=true"
url: "https://cars-survey.github.io"
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - members.md
theme: jekyll-theme-minimal
